baseURL = 'https://cjon.dev/'
languageCode = 'en-us'
title = "cjon's blog"
theme = 'papermod'

copyright = "Â© 2024 Cullen J. O'Neill"

[Params]
  favicon="favicon32x32.png"

[markup]
  [markup.highlight]
    style = 'doom-one'
